import Head from 'next/head';
import Link from 'next/link';
import Avatar from '../components/Avatar';

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Privacy · DG AI Coach</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div style={s.page}>
        <Link href="/" style={s.brandLink}>
          <Avatar kind="coach" size={32} />
          <span style={s.brandName}>DG AI Coach</span>
        </Link>

        <article style={s.article}>
          <h1 style={s.h1}>Privacy</h1>
          <p style={s.updated}>Last updated: April 2026</p>

          <h2 style={s.h2}>What we collect</h2>
          <p>When you use DG AI Coach, we store:</p>
          <ul style={s.ul}>
            <li>Your account info: name, email, hashed password (we never see the plaintext).</li>
            <li>Your coaching messages on web and Telegram, your task submissions, and the coach's replies.</li>
            <li>A distilled "memory" doc the coach uses to personalize future sessions: your role, goal, prompt style, observed strengths, and open threads.</li>
            <li>Your XP, level, achievements, awards, and activity log entries.</li>
            <li>If you upload a photo, the image data URL is stored on your user record.</li>
            <li>If you pair Telegram, your Telegram user ID and (where permitted) your profile photo URL.</li>
          </ul>

          <h2 style={s.h2}>How we use it</h2>
          <ul style={s.ul}>
            <li>To deliver coaching, generate replies, score your task submissions, and build your dashboard.</li>
            <li>To send your messages to the underlying AI provider (Anthropic, makers of Claude) for processing. We do not train models on your data.</li>
            <li>To improve the product internally — anonymized aggregate insights only.</li>
            <li>We do <strong>not</strong> sell your data, ever.</li>
          </ul>

          <h2 style={s.h2}>What you should know about AI</h2>
          <ul style={s.ul}>
            <li>Coach replies are generated by AI. They can be wrong. Verify anything that matters with a primary source.</li>
            <li>The coach is explicitly told not to give medical, legal, or financial advice. If you ask, it will refer you to a qualified professional.</li>
            <li>Don't paste passwords, full customer records, salary information, contracts, or other sensitive data into the chat. The coach will warn you when you're about to do this.</li>
          </ul>

          <h2 style={s.h2}>Your controls</h2>
          <ul style={s.ul}>
            <li><strong>Your data, on demand.</strong> Email <a href="mailto:sopheap.hin@gmail.com">sopheap.hin@gmail.com</a> to export or delete your account. We respond within 7 days.</li>
            <li><strong>Reset your coach memory.</strong> Admin can wipe your distilled memory; ask via the same email.</li>
            <li><strong>Stop anytime.</strong> Sign out from the dashboard menu. Telegram users can block the bot.</li>
          </ul>

          <h2 style={s.h2}>Where data lives</h2>
          <p>
            All learner data is stored in Google Firestore (Firebase project <code>cambodia-ai-group</code>). Anthropic processes the conversation content under their{' '}
            <a href="https://www.anthropic.com/legal/privacy" target="_blank" rel="noreferrer">privacy policy</a>. Telegram messages pass through Telegram's servers under{' '}
            <a href="https://telegram.org/privacy" target="_blank" rel="noreferrer">Telegram's privacy policy</a>.
          </p>

          <h2 style={s.h2}>Contact</h2>
          <p>
            DG AI Coach is operated by Cambodia AI Group / DG Academy in Phnom Penh, Cambodia. For questions, write to{' '}
            <a href="mailto:sopheap.hin@gmail.com">sopheap.hin@gmail.com</a>.
          </p>

          <div style={s.footer}>
            <Link href="/terms" style={{ color: '#7A7670' }}>Terms of use →</Link>
          </div>
        </article>

        <style jsx global>{`
          html, body { margin: 0; padding: 0; background: #FAF9F5; color: #2A2925; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", "Inter", sans-serif; -webkit-font-smoothing: antialiased; }
          a { color: #C96442; }
        `}</style>
      </div>
    </>
  );
}

const s = {
  page:       { maxWidth: 720, margin: '0 auto', padding: '32px 24px 80px' },
  brandLink:  { display: 'flex', alignItems: 'center', gap: 10, color: '#2A2925', textDecoration: 'none', marginBottom: 32 },
  brandName:  { fontWeight: 600, fontSize: 15 },
  article:    { fontSize: 15, lineHeight: 1.7 },
  h1:         { fontSize: 32, fontWeight: 600, letterSpacing: -0.6, margin: '0 0 6px' },
  updated:    { color: '#7A7670', fontSize: 13, margin: '0 0 32px' },
  h2:         { fontSize: 18, fontWeight: 600, margin: '32px 0 8px' },
  ul:         { margin: '8px 0 8px 22px', padding: 0 },
  footer:     { marginTop: 40, paddingTop: 20, borderTop: '1px solid #EBE8DD' },
};
