import Head from 'next/head';
import Link from 'next/link';
import Avatar from '../components/Avatar';

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of use · DG AI Coach</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div style={s.page}>
        <Link href="/" style={s.brandLink}>
          <Avatar kind="coach" size={32} />
          <span style={s.brandName}>DG AI Coach</span>
        </Link>

        <article style={s.article}>
          <h1 style={s.h1}>Terms of use</h1>
          <p style={s.updated}>Last updated: April 2026</p>

          <h2 style={s.h2}>What this is</h2>
          <p>
            DG AI Coach is a coaching service for working professionals built on top of large language models. It is provided by Cambodia AI Group / DG Academy. The service is currently in pilot — features and pricing may evolve.
          </p>

          <h2 style={s.h2}>Acceptable use</h2>
          <ul style={s.ul}>
            <li>Use it for your own professional development. Do not use it to harass, deceive, or harm others.</li>
            <li>Do not paste data you don't have the right to share — customer records, employee data, contracts, IP, passwords, etc.</li>
            <li>Don't try to break, scrape, or abuse the service. We rate-limit and ban as needed.</li>
            <li>The coach's outputs are for guidance only. Use your own judgment for any consequential decision.</li>
          </ul>

          <h2 style={s.h2}>About AI replies</h2>
          <ul style={s.ul}>
            <li>Coach replies are generated by Claude (by Anthropic). They are pattern-matched language, not professional advice.</li>
            <li>The coach is instructed not to give medical, legal, or financial advice and will refer you to a qualified professional. Treat any AI output in those domains with extra skepticism.</li>
            <li>AI can hallucinate facts and citations. If a claim matters, verify it.</li>
            <li>You remain accountable for actions you take based on AI guidance — the coach is a tool, not a decision-maker.</li>
          </ul>

          <h2 style={s.h2}>Account and data</h2>
          <ul style={s.ul}>
            <li>You can sign up with email + password, or use the service anonymously via cookie session.</li>
            <li>Anonymous sessions can be upgraded to a real account later — your progress carries over.</li>
            <li>You can delete your account by emailing <a href="mailto:sopheap.hin@gmail.com">sopheap.hin@gmail.com</a>.</li>
            <li>Free during the pilot. We'll give you 30 days notice before introducing pricing.</li>
          </ul>

          <h2 style={s.h2}>Limitations of liability</h2>
          <p>
            DG AI Coach is provided "as is", without warranty. To the maximum extent permitted by law, Cambodia AI Group is not liable for damages arising from use of the service, including AI-generated content. By using DG AI Coach, you accept these limits.
          </p>

          <h2 style={s.h2}>Changes</h2>
          <p>
            We may update these terms. We'll change the "last updated" date and, for material changes, notify you by email or in-app.
          </p>

          <h2 style={s.h2}>Contact</h2>
          <p>
            For anything: <a href="mailto:sopheap.hin@gmail.com">sopheap.hin@gmail.com</a>. Hin Sopheap, Co-founder and Executive Director, DG Academy / Cambodia AI Group, Phnom Penh.
          </p>

          <div style={s.footer}>
            <Link href="/privacy" style={{ color: '#7A7670' }}>← Privacy</Link>
          </div>
        </article>

        <style jsx global>{`
          html, body { margin: 0; padding: 0; background: #FAF9F5; color: #2A2925; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", "Inter", sans-serif; -webkit-font-smoothing: antialiased; }
          a { color: #C96442; }
        `}</style>
      </div>
    </>
  );
}

const s = {
  page:       { maxWidth: 720, margin: '0 auto', padding: '32px 24px 80px' },
  brandLink:  { display: 'flex', alignItems: 'center', gap: 10, color: '#2A2925', textDecoration: 'none', marginBottom: 32 },
  brandName:  { fontWeight: 600, fontSize: 15 },
  article:    { fontSize: 15, lineHeight: 1.7 },
  h1:         { fontSize: 32, fontWeight: 600, letterSpacing: -0.6, margin: '0 0 6px' },
  updated:    { color: '#7A7670', fontSize: 13, margin: '0 0 32px' },
  h2:         { fontSize: 18, fontWeight: 600, margin: '32px 0 8px' },
  ul:         { margin: '8px 0 8px 22px', padding: 0 },
  footer:     { marginTop: 40, paddingTop: 20, borderTop: '1px solid #EBE8DD' },
};
